### ISSUE TITLE
Add acceptance tests for multiply

### ISSUE THREAD

**Issue by eokwara0** [eokwara0/NodeJs-Calculator-API#1]
### Todo : 
- [ ] create and write tests for multiply route
- [ ] test for invalid routes
- [ ] test for valid routes
- [ ] test for invalid value inputs
